name: Lint

on:
    pull_request:
    push:
        branches: [main]
    workflow_dispatch:

permissions: {}

jobs:
    lints:
        name: linters
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
              with:
                  persist-credentials: false
            - uses: jdx/mise-action@9dc7d5dd454262207dea3ab5a06a3df6afc8ff26 # v3.4.1

            - name: Shellcheck
              run: |
                  SUPPORTED_SHELLS="sh|bash"
                  rg --ignore --hidden -l "^#!(.*/|.*env +)($SUPPORTED_SHELLS)" . \
                      | xargs -r -t shellcheck

            - name: shfmt
              # shfmt -w -i 4 -s -bn -ci -sr -kp .
              run: |
                  SUPPORTED_SHELLS="sh|bash"
                  rg --ignore --hidden -l "^#!(.*/|.*env +)($SUPPORTED_SHELLS)" . \
                      | xargs -r -t shfmt -d -i 4 -s -bn -ci -sr -kp

            - name: Zizmor
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: zizmor .

            - name: Actionlint
              run: actionlint

            - name: Typos
              run: typos
